#!/usr/bin/perl

use Huhu::DSL;

=begin

Install packages

=cut

install {
    packages => [
        qw(php5-memcache mysql-client pwgen php5 php5-fpm
          php-apc mailutils php-mail php5-mysql php5-mcrypt php5-memcache php5-gd
          php5-curl git-core)
    ]
};

=begin

Create directories, set permissions, and install required files

=cut

fs {directories => [
        {   dir   => '/mnt/tmp',
            chmod => 1777
        },
        {   dir   => '/mnt/logs/php-fpm',
            chmod => 1777
        },
        {   dir   => '/mnt/ramdisk/proxy-cache',
            chmod => 1777
        },
        {   dir   => '/mnt/ramdisk/phpfpm-cache',
            chmod => 1777
        },
        {   file => 'files/php/php5_fpm_pool.d_www.conf',
            dst  => '/etc/php5/fpm/pool.d/www.conf'
        }
    ];
};
